### ISSUE TITLE
can't install, node standalone.js fails

### ISSUE THREAD

**Issue by luckydonald** [AlexanderDzhoganov/pipboyclient#1]
First of all: Huge thanks for making this!

I am not quite sure how to get it working.
![2015-12-10 10_25_05-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/2737108/11711660/555214cc-9f28-11e5-95c2-9fff135e62b9.png)

and the app can't connect
![2015-12-10 10_27_15-fallout 4 pip-boy](https://cloud.githubusercontent.com/assets/2737108/11711686/87e37110-9f28-11e5-8beb-e5954660e56a.png)

**Comment by AlexanderDzhoganov** [comment]
Hey, this project is dead, all the code has been moved [to the new project instead](https://github.com/RobCoIndustries/pipboy).

**Comment by luckydonald** [comment]
Could you please add a link to the Readme, to make it clear for other users, too?

**Comment by AlexanderDzhoganov** [comment]
Sure, done.
